stages:
  - test
  - deploy

test3.9:
  stage: test
  script:
  - python3.9 --version
  - pip3.9 -V
  - python3.9 -m venv ENV3.9
  - source ENV3.9/bin/activate
  - pip3.9 install -r ci-requirements.txt
  - ruff --exclude="ENV3.9" .
  - mypy core pandabackup viewer --exclude viewer/migrations
  - bash ./set_db_engine.sh
  - python3.9 manage.py migrate
  - python3.9 manage.py test viewer.tests.test_internal viewer.tests.test_core
  cache:
    paths:
    - .mypy_cache
    - .ruff_cache
  tags:
    - django

test3.10:
  stage: test
  script:
  - python3.10 --version
  - pip3.10 -V
  - python3.10 -m venv ENV3.10
  - source ENV3.10/bin/activate
  - pip3.10 install -r ci-requirements.txt
  - ruff --exclude="ENV3.10" .
  - mypy core pandabackup viewer --exclude viewer/migrations
  - bash ./set_db_engine.sh
  - python3.10 manage.py migrate
  - python3.10 manage.py test viewer.tests.test_internal viewer.tests.test_core
  cache:
    paths:
    - .mypy_cache
    - .ruff_cache
  tags:
    - django

test3.11:
  stage: test
  script:
  - python3.11 --version
  - pip3.11 -V
  - python3.11 -m venv ENV3.11
  - source ENV3.11/bin/activate
  - pip3.11 install -r ci-requirements.txt
  - ruff --exclude="ENV3.11" .
  - mypy core pandabackup viewer --exclude viewer/migrations
  - bash ./set_db_engine.sh
  - python3.11 manage.py migrate
  - python3.11 manage.py test viewer.tests.test_internal viewer.tests.test_core
  cache:
    paths:
    - .mypy_cache
    - .ruff_cache
  tags:
    - django

deploy_review:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SERVER_PRIV_KEY_REVIEW")
  script:
    - rsync -av --delete --exclude='.gitlab-ci.yml' --exclude='.git/' --exclude='static/' --exclude settings.ini --exclude settings.yaml . ${SERVER_REMOTE_ADDR_REVIEW}:${SERVER_REMOTE_DIR_REVIEW}
    - ssh $SERVER_REMOTE_ADDR_REVIEW "cd $SERVER_REMOTE_DIR_REVIEW && python3.9 -m venv ENV && source ENV/bin/activate && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && {{test -f ./current.pid && cat ./current.pid | xargs kill -9} || true } && python server.py -d -pf ./current.pid"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $SERVER_URL_REVIEW
  only:
    - trunk
  tags:
    - django

deploy_prod:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SERVER_PRIV_KEY_PROD")
  script:
    - rsync -av --delete --exclude='.gitlab-ci.yml' --exclude='.git/' --exclude='static/' --exclude settings.ini --exclude settings.yaml . ${SERVER_REMOTE_ADDR_PROD}:${SERVER_REMOTE_DIR_PROD}
    - ssh $SERVER_REMOTE_ADDR_PROD "cd $SERVER_REMOTE_DIR_PROD && python3.9 -m venv ENV && source ENV/bin/activate && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && {{test -f ./current.pid && cat ./current.pid | xargs kill -9} || true } && python server.py -d -pf ./current.pid"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $SERVER_URL_PROD
  when: manual
  only:
    - trunk
  tags:
    - django